# Generated by Django 2.2.7 on 2021-01-22 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=50, verbose_name='plan')),
                ('date', models.DateField(verbose_name='date')),
                ('price', models.IntegerField(verbose_name='price')),
                ('expire', models.CharField(default='No', max_length=50, verbose_name='expire_plan')),
                ('active', models.CharField(default='Yes', max_length=50, verbose_name='active')),
                ('mangerref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subref', to='manager.Manager')),
            ],
            options={
                'db_table': 'Subscription',
            },
        ),
    ]
