# Generated by Django 2.2.7 on 2021-01-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='expireDate',
            field=models.DateField(null=True, verbose_name='expire_date'),
        ),
    ]
