# Generated by Django 2.2.7 on 2021-01-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscription_expiredate'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='traxid',
            field=models.CharField(max_length=100, null=True, verbose_name='transaction_id'),
        ),
    ]
