# Generated by Django 2.2.7 on 2021-01-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscription_traxid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='traxid',
            new_name='transactionId',
        ),
    ]
